Repository vtex/openapi-schemas, pull requests merged in 2025-04, with the labels that each got.

#1412 EDU-14708 - Change param default
  VTEX - Orders API.json
Labels: documentation

#1415 EDU-14388 - Add field on order modifications requests
  VTEX - Orders API.json
Labels: documentation

#1419 EDU-12753 fix: fix description errors
  VTEX - Checkout API.json
Labels: documentation

#1422 EDU-12753 fix: fix distance type
  VTEX - Checkout API.json
Labels: documentation

#1423 EDU-12753 fix: add response schema
  VTEX - Checkout API.json
Labels: documentation

#1424 EDU-12753 fix: add descriptions to items
  VTEX - Checkout API.json
Labels: documentation

#1421 EDU-14834 - Add `clientprofiledata` field
  VTEX - Orders API.json
Labels: documentation

#1427 Edu 14876 campo dock time fake
  VTEX - Logistics API.json
Labels: documentation

#1413 Feat/EDU-14815-new-Delivery-Promise-Notification-API
  VTEX - Delivery Promise Notification API.json
Labels: documentation

#1430 Update VTEX - Logistics API.json
  VTEX - Logistics API.json
Labels: bug

#1431 EDU-7754 - Add order state
  VTEX - Orders API.json
Labels: documentation

#1391 EDU-14427-new-pick-pack-api
  PostmanCollections/VTEX - Pick and Pack API.json
  VTEX - Pick and Pack API.json
Labels: documentation

#1440 fix: add endpoint link
  VTEX - Pick and Pack API.json
Labels: documentation

#1443 EDU-15030 Removing comma error (#1442)
  VTEX - Marketplace Protocol - External Marketplace Mapper.json
Labels: bug, documentation
